[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_dungeons = "CW7thTzLfzZop6TtHrD4FgjcJzxNMiscHRR9XrdW4T14"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
